type ytcfg = {
  EXPERIMENT_FLAGS: object;
  INNERTUBE_API_KEY: string;
  INNERTUBE_API_VERSION: string;
  INNERTUBE_CLIENT_NAME: string;
  INNERTUBE_CLIENT_VERSION: string;
  INNERTUBE_CONTEXT: object;
  INNERTUBE_CONTEXT_CLIENT_NAME: number;
  INNERTUBE_CONTEXT_CLIENT_VERSION: number;
  LATEST_ECATCHER_SERVICE_TRACKING_PARAMS: object;
};

export default ytcfg;
